name = "duelist-emporium"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

# Production database configuration
# You'll need to create this in Cloudflare dashboard
[[d1_databases]]
binding = "DB"
database_name = "duelist-emporium-production"
database_id = "YOUR_DATABASE_ID_HERE"

# Environment variables (set these as secrets in Cloudflare Pages)
# RESEND_API_KEY - Your Resend API key for email notifications
# OWNER_EMAIL - Your email address for order notifications